### ISSUE TITLE
카드 컴포넌트 수정

### ISSUE THREAD

**Issue by again7536** [TeamNoguzi/LetsKlay#32]
## 개발 사항
- [x] 하나로 합쳐주세요~ (컴포넌트 사이즈가 작아서 합치는게 나을듯)
```jsx
const CardProgress: React.FC<ProgressProps> = (props: ProgressProps) => {
  return (
    <div className="mt-auto">
      <div>
        <span>${props.price}</span>
        <span className="float-end">
          {props.progress.percent}% of ${props.progress.totalPrice.toLocaleString("en")}
        </span>
      </div>
      <ProgressBar now={props.progress.percent} />
    </div>
  );
};

const ItemCard: React.FC<CardProps> = ({ mode, title, subtitle, cardText, price, progress }) => {
  return (
    <Card className={styles["item-card"]}>
      <Card.Img className={styles["card-img"]} variant="top" src={doge} />
      <Card.Body className={styles["card-body"]}>
        <Card.Title>{title}</Card.Title>
        <Card.Subtitle className={styles["sub-title"]}>{subtitle}</Card.Subtitle>
          <Card.Text className = {styles["card-text"]}> {mode==='Default'?cardText:undefined} </Card.Text> 
        <CardProgress price={price} progress={progress} />
      </Card.Body>
    </Card>
  );
};
```
- [x] progress는 카드 내부에서 계산하고 maxPrice만 받아오도록
- [x]  mode의 타입을 명확히 지정 (mode : 'big' | 'small')
```typescript
interface CardProps {
  mode : string;
  title: string;
  subtitle: string;
  cardText: string;
  price: number;
  progress: {
    percent: number;
    totalPrice: number;
  };
}
```

- [x] width 고정 풀고 max-width로 제한하기
```css
.item-card {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  padding: 0px;

  width: 318px;

  height: auto;

  /* Global/09. White */

  background: #ffffff;
  /* Components/Card border */

  border: 1px solid #dfdfdf;
  box-sizing: border-box;
  border-radius: 4px;

  /* Inside auto layout */
  flex: none;
  order: 0;
  align-self: stretch;
  flex-grow: 0;
  margin: 0px 0px;
}
```
### 참고 사항
- 변경 후 캐러셀에 영향 없도록 해주세요
- #30 변경 사항 참조
